CONTENT = [
    {
        "format": "System explainer",
        "pillar": "Branding",
        "title": "Brand bukan logo.\nBrand adalah sistem.",
        "subtitle": "Strategi, visual, bahasa, dan pengalaman harus menyampaikan janji yang sama.",
        "caption": "Logo hanyalah salah satu tanda pengenal. Brand dibentuk oleh alasan bisnis untuk dipilih, siapa audiensnya, apa yang dijanjikan, bagaimana cara berbicara, seperti apa tampilannya, dan bagaimana pengalaman itu diberikan. Ketika semuanya selaras, tamu lebih cepat memahami nilai bisnis dan lebih mudah mengingatnya.",
        "cta": "Simpan sebagai fondasi branding bisnis hospitality-mu.",
        "hashtags": "#BrandingSystem #HospitalityBranding #BrandStrategy #Lajora",
        "diagram": "loop",
        "steps": ["Strategi", "Identitas", "Bahasa", "Pengalaman"],
    },
    {
        "format": "Process",
        "pillar": "Branding",
        "title": "Bagaimana sebuah\nbrand dibangun?",
        "subtitle": "Mulai dari keputusan bisnis, bukan dari memilih warna.",
        "caption": "Proses branding yang sehat dimulai dari riset bisnis dan audiens. Setelah itu kita menentukan positioning, menyusun pesan, membangun identitas visual, menerapkannya ke seluruh touchpoint, lalu mengukur respons pasar. Urutan ini membuat desain memiliki alasan dan membantu tim mengambil keputusan secara konsisten.",
        "cta": "Riset → Positioning → Pesan → Identitas → Implementasi.",
        "hashtags": "#BrandProcess #BrandDevelopment #HospitalityBusiness #Lajora",
        "diagram": "flow",
        "steps": ["Riset", "Positioning", "Pesan", "Identitas", "Implementasi"],
    },
    {
        "format": "Framework",
        "pillar": "Positioning",
        "title": "Positioning adalah\nalasan untuk dipilih.",
        "subtitle": "Bukan berusaha menarik semua orang, tetapi menjadi paling relevan bagi audiens yang tepat.",
        "caption": "Positioning menjawab tiga pertanyaan: siapa tamu utama kita, kebutuhan apa yang paling penting bagi mereka, dan alasan apa yang membuat kita berbeda. Jawaban yang tajam membantu bisnis menentukan penawaran, harga, pengalaman, konten, dan channel pemasaran tanpa bergerak ke terlalu banyak arah.",
        "cta": "Lengkapi kalimat: bisnis kami dipilih karena…",
        "hashtags": "#BrandPositioning #HospitalityStrategy #BusinessClarity #Lajora",
        "diagram": "target",
        "steps": ["Audiens", "Kebutuhan", "Pembeda", "Alasan memilih"],
    },
    {
        "format": "Educational",
        "pillar": "Brand voice",
        "title": "Brand harus terdengar\nseperti siapa?",
        "subtitle": "Tone of voice membuat website, chat, caption, dan pelayanan terasa berasal dari satu karakter.",
        "caption": "Brand voice menentukan kepribadian yang konsisten dalam kata-kata. Apakah hangat, tenang, berani, personal, atau sangat efisien? Setelah karakter dipilih, kita menyusun contoh kalimat, kata yang digunakan, kata yang dihindari, dan cara merespons tamu. Hasilnya: komunikasi terasa lebih manusiawi dan mudah dikenali.",
        "cta": "Audit apakah caption dan chat-mu terdengar seperti brand yang sama.",
        "hashtags": "#BrandVoice #ToneOfVoice #HospitalityCommunication #Lajora",
        "diagram": "stack",
        "steps": ["Karakter", "Pilihan kata", "Gaya kalimat", "Respons tamu"],
    },
    {
        "format": "System explainer",
        "pillar": "Visual identity",
        "title": "Identitas visual harus\nbisa menjadi sistem.",
        "subtitle": "Logo, warna, tipografi, foto, ikon, dan layout bekerja sebagai satu bahasa visual.",
        "caption": "Identitas visual yang kuat bukan kumpulan elemen yang cantik. Setiap elemen memiliki fungsi dan aturan agar tim bisa membuat website, feed, promosi, signage, dan materi operasional dengan cepat. Sistem yang jelas menjaga kualitas sekaligus mengurangi keputusan desain yang berulang.",
        "cta": "Visual yang konsisten mempercepat kerja dan memperkuat ingatan.",
        "hashtags": "#VisualIdentity #BrandSystem #HospitalityDesign #Lajora",
        "diagram": "grid",
        "steps": ["Logo", "Warna", "Tipografi", "Fotografi", "Layout", "Ikon"],
    },
    {
        "format": "Checklist",
        "pillar": "Rebranding",
        "title": "Kapan rebranding\nmenjadi perlu?",
        "subtitle": "Saat identitas lama tidak lagi mewakili kualitas, target pasar, atau arah bisnis.",
        "caption": "Rebranding layak dilakukan ketika bisnis sulit dibedakan, visual tidak konsisten, target tamu berubah, layanan berkembang, atau pengalaman nyata sudah jauh lebih baik daripada tampilannya. Tujuan rebranding bukan sekadar terlihat baru, melainkan membuat persepsi pasar kembali sesuai dengan nilai bisnis.",
        "cta": "Perbarui alasan bisnisnya, lalu perbarui ekspresinya.",
        "hashtags": "#Rebranding #BrandAudit #HospitalityGrowth #Lajora",
        "diagram": "checklist",
        "steps": ["Sulit dibedakan", "Target berubah", "Layanan berkembang", "Visual tertinggal"],
    },
    {
        "format": "Journey",
        "pillar": "Brand experience",
        "title": "Brand hidup di setiap\ntitik perjalanan tamu.",
        "subtitle": "Discovery, website, booking, pembayaran, pelayanan, dan komunikasi setelah kunjungan.",
        "caption": "Tamu membentuk persepsi dari rangkaian pengalaman, bukan dari satu desain. Konten pertama menciptakan ekspektasi. Website memberi keyakinan. Booking dan pembayaran menunjukkan profesionalitas. Pelayanan membuktikan janji. Komunikasi setelah kunjungan membuka peluang kembali. Branding menyatukan semuanya.",
        "cta": "Petakan touchpoint yang paling lemah minggu ini.",
        "hashtags": "#BrandExperience #GuestJourney #HospitalityBrand #Lajora",
        "diagram": "journey",
        "steps": ["Discover", "Explore", "Book", "Experience", "Return"],
    },
    {
        "format": "Educational",
        "pillar": "Owned website",
        "title": "Website sendiri adalah\naset penjualan milikmu.",
        "subtitle": "Kamu mengendalikan cerita, penawaran, data, dan perjalanan menuju transaksi.",
        "caption": "Di website sendiri, bisnis bebas menentukan cara tampil, paket yang ditawarkan, informasi yang ditonjolkan, dan bagaimana tamu diarahkan menuju booking. Traffic yang datang tidak berhenti sebagai kunjungan; ia bisa menjadi data, percakapan, transaksi, dan hubungan jangka panjang.",
        "cta": "Marketplace memberi jangkauan. Website memberi kendali.",
        "hashtags": "#OwnedWebsite #DirectBooking #HospitalityWebsite #Lajora",
        "diagram": "ownership",
        "steps": ["Konten", "Penawaran", "Data", "Transaksi", "Relasi"],
    },
    {
        "format": "Ecosystem",
        "pillar": "Direct booking",
        "title": "Direct booking adalah\nsebuah ekosistem.",
        "subtitle": "Website, booking engine, payment, notifikasi, inventori, dan database bekerja bersama.",
        "caption": "Tombol Book Now hanya bagian depan. Di belakangnya terdapat ketersediaan kamar, aturan harga, metode pembayaran, email atau WhatsApp konfirmasi, pencatatan tamu, dan sinkronisasi inventori. Ketika terintegrasi, tim bekerja lebih rapi dan tamu mendapatkan kepastian lebih cepat.",
        "cta": "Bangun sistemnya, bukan hanya halaman websitenya.",
        "hashtags": "#DirectBookingSystem #BookingEngine #HospitalityTech #Lajora",
        "diagram": "hub",
        "steps": ["Website", "Inventory", "Payment", "Notification", "Guest data"],
    },
    {
        "format": "Flow",
        "pillar": "Booking flow",
        "title": "Alur booking yang baik\nmengurangi keraguan.",
        "subtitle": "Pilih tanggal, lihat pilihan, isi data, bayar, lalu langsung terkonfirmasi.",
        "caption": "Setiap langkah booking harus menjawab satu kebutuhan tanpa membingungkan. Tanggal dan jumlah tamu menentukan ketersediaan. Pilihan kamar menjelaskan manfaat. Data tamu dibuat ringkas. Pembayaran transparan. Konfirmasi tampil segera. Semakin jelas alurnya, semakin kecil peluang tamu berhenti di tengah.",
        "cta": "Kurangi langkah yang tidak membantu keputusan.",
        "hashtags": "#BookingFlow #ConversionDesign #HotelWebsite #Lajora",
        "diagram": "flow",
        "steps": ["Tanggal", "Pilihan", "Data tamu", "Pembayaran", "Konfirmasi"],
    },
    {
        "format": "System explainer",
        "pillar": "Booking engine",
        "title": "Apa yang dikerjakan\nbooking engine?",
        "subtitle": "Menghubungkan ketersediaan, harga, aturan, add-on, pembayaran, dan konfirmasi.",
        "caption": "Booking engine membaca tanggal, unit yang tersedia, kapasitas, harga, minimum stay, promo, dan kebijakan. Setelah tamu memilih, sistem menghitung total, menerima pembayaran, mengunci inventori, lalu mengirim konfirmasi. Inilah mesin transaksi di balik website direct booking.",
        "cta": "Website menarik perhatian; booking engine menyelesaikan transaksi.",
        "hashtags": "#BookingEngine #HospitalitySystem #DirectReservation #Lajora",
        "diagram": "engine",
        "steps": ["Availability", "Rate rules", "Add-ons", "Payment", "Confirmation"],
    },
    {
        "format": "Integration",
        "pillar": "Channel manager",
        "title": "Satu inventori untuk\nbanyak kanal.",
        "subtitle": "Channel manager membantu memperbarui ketersediaan dan mengurangi risiko overbooking.",
        "caption": "Ketika kamar dijual melalui website sendiri dan beberapa marketplace, inventori perlu bergerak sebagai satu sumber data. Channel manager menerima reservasi dari berbagai kanal lalu memperbarui ketersediaan. Sistem ini membantu tim mengurangi pekerjaan manual dan risiko unit terjual dua kali.",
        "cta": "Integrasi membuat direct booking hidup berdampingan dengan OTA.",
        "hashtags": "#ChannelManager #HotelInventory #BookingIntegration #Lajora",
        "diagram": "hub",
        "steps": ["Website", "OTA A", "OTA B", "Inventory", "Reservation"],
    },
    {
        "format": "Conversion",
        "pillar": "Website UX",
        "title": "Website harus menjawab\nsebelum tamu bertanya.",
        "subtitle": "Foto, fasilitas, lokasi, kebijakan, ulasan, harga, dan CTA tersedia di momen yang tepat.",
        "caption": "Conversion tumbuh ketika informasi penting mudah ditemukan. Tamu ingin memahami pengalaman, membandingkan pilihan, memastikan biaya, membaca kebijakan, dan merasa aman sebelum membayar. Website yang baik mengatur urutan informasi sesuai cara tamu mengambil keputusan.",
        "cta": "Desain bukan dekorasi. Desain adalah pengurangan keraguan.",
        "hashtags": "#WebsiteConversion #HospitalityUX #DirectBookingWebsite #Lajora",
        "diagram": "funnel",
        "steps": ["Attention", "Interest", "Trust", "Decision", "Booking"],
    },
    {
        "format": "Mobile first",
        "pillar": "Website UX",
        "title": "Booking paling sering\ndimulai dari layar kecil.",
        "subtitle": "Mobile-first berarti cepat, terbaca, mudah disentuh, dan nyaman diselesaikan.",
        "caption": "Di HP, ruang terbatas dan perhatian cepat berpindah. Website perlu memprioritaskan kecepatan, ukuran teks, tombol yang jelas, galeri ringan, formulir ringkas, dan metode pembayaran yang familiar. Pengalaman desktop yang diperkecil belum tentu menjadi pengalaman mobile yang baik.",
        "cta": "Audit seluruh booking flow dari satu tangan.",
        "hashtags": "#MobileFirst #HospitalityWebsite #BookingUX #Lajora",
        "diagram": "phone",
        "steps": ["Fast load", "Clear CTA", "Short form", "Easy payment"],
    },
    {
        "format": "Data explainer",
        "pillar": "First-party data",
        "title": "Website sendiri membangun\ndata milik sendiri.",
        "subtitle": "Sumber kunjungan, minat, transaksi, dan riwayat tamu dapat dipakai untuk keputusan berikutnya.",
        "caption": "Dengan persetujuan dan pengelolaan yang tepat, website memberi first-party data: dari mana orang datang, halaman apa yang dilihat, penawaran apa yang menarik, hingga siapa yang pernah booking. Data ini membantu remarketing, personalisasi, evaluasi campaign, dan strategi repeat guest.",
        "cta": "Data yang rapi mengubah pemasaran dari tebakan menjadi keputusan.",
        "hashtags": "#FirstPartyData #HospitalityMarketing #GuestData #Lajora",
        "diagram": "data",
        "steps": ["Traffic source", "Interest", "Booking", "Guest profile", "Repeat"],
    },
    {
        "format": "Payment flow",
        "pillar": "Payment gateway",
        "title": "Bagaimana payment\ngateway bekerja?",
        "subtitle": "Tamu memilih metode, sistem memproses, status dikirim, dan booking diperbarui otomatis.",
        "caption": "Alur sederhananya: website membuat tagihan, payment gateway menampilkan metode pembayaran, penyedia pembayaran memproses transaksi, lalu gateway mengirim status berhasil atau gagal ke sistem booking. Setelah tervalidasi, reservasi dikonfirmasi dan bukti pembayaran dikirim.",
        "cta": "Payment gateway menghubungkan transaksi dengan operasional.",
        "hashtags": "#PaymentGateway #PaymentFlow #BookingSystem #Lajora",
        "diagram": "flow",
        "steps": ["Invoice", "Payment method", "Processing", "Webhook", "Confirmed"],
    },
    {
        "format": "Educational",
        "pillar": "Payment options",
        "title": "Berikan metode bayar\nyang sudah dipercaya tamu.",
        "subtitle": "Transfer virtual account, kartu, e-wallet, dan QR dapat berada dalam satu alur.",
        "caption": "Pilihan pembayaran yang familiar mengurangi hambatan di langkah terakhir. Metode yang ditampilkan dapat disesuaikan dengan pasar, nominal transaksi, kebutuhan deposit, dan kebijakan bisnis. Semua status tetap kembali ke satu sistem agar tim tidak perlu memeriksa pembayaran satu per satu.",
        "cta": "Lebih banyak metode, tetap satu rekonsiliasi.",
        "hashtags": "#OnlinePayment #VirtualAccount #EWallet #PaymentIntegration #Lajora",
        "diagram": "grid",
        "steps": ["Virtual account", "Card", "E-wallet", "QR payment", "Bank transfer", "Deposit"],
    },
    {
        "format": "Trust",
        "pillar": "Payment security",
        "title": "Kepercayaan menentukan\napakah tamu berani membayar.",
        "subtitle": "Rincian biaya, kebijakan, domain aman, dan status transaksi harus terlihat jelas.",
        "caption": "Sistem pembayaran yang terasa aman bukan hanya urusan teknologi. Tamu perlu melihat total biaya, pajak, kebijakan pembatalan, identitas bisnis, koneksi HTTPS, dan konfirmasi status. Transparansi mengurangi keraguan sekaligus menurunkan beban pertanyaan untuk tim.",
        "cta": "Jelaskan setiap rupiah sebelum meminta pembayaran.",
        "hashtags": "#PaymentSecurity #CustomerTrust #HospitalityPayment #Lajora",
        "diagram": "shield",
        "steps": ["HTTPS", "Clear total", "Policy", "Status", "Receipt"],
    },
    {
        "format": "Operations",
        "pillar": "Settlement",
        "title": "Setelah tamu membayar,\napa yang terjadi?",
        "subtitle": "Status, settlement, rekonsiliasi, pembatalan, dan refund perlu alur yang rapi.",
        "caption": "Transaksi berhasil hanyalah awal proses operasional. Sistem mencatat payment ID, memperbarui reservasi, mengirim notifikasi, menunggu settlement, lalu mencocokkan dana. Jika terjadi pembatalan, tim memiliki jejak untuk refund dan perubahan status. Alur yang terdokumentasi mengurangi kesalahan manual.",
        "cta": "Bangun SOP pembayaran bersama integrasinya.",
        "hashtags": "#PaymentOperations #Settlement #Reconciliation #HospitalityTech #Lajora",
        "diagram": "timeline",
        "steps": ["Paid", "Recorded", "Settled", "Reconciled", "Refund if needed"],
    },
    {
        "format": "Restaurant system",
        "pillar": "Table booking",
        "title": "Reservasi meja juga bisa\nberjalan otomatis.",
        "subtitle": "Pilih waktu, jumlah tamu, area, add-on, deposit, lalu terkonfirmasi.",
        "caption": "Sistem reservasi restoran dapat mengatur slot waktu, kapasitas meja, area, minimum spend, pre-order, dan deposit. Setelah pembayaran berhasil, meja dikunci dan tamu menerima konfirmasi. Tim mendapat daftar reservasi yang rapi tanpa mengulang percakapan yang sama.",
        "cta": "Satu flow untuk tamu, dapur, kasir, dan front-of-house.",
        "hashtags": "#TableBooking #RestaurantSystem #ReservationTechnology #Lajora",
        "diagram": "flow",
        "steps": ["Time slot", "Party size", "Table", "Deposit", "Confirmed"],
    },
    {
        "format": "Automation",
        "pillar": "Notification",
        "title": "Konfirmasi otomatis\nmengurangi pekerjaan manual.",
        "subtitle": "Email dan WhatsApp dapat merespons event booking secara real-time.",
        "caption": "Ketika booking dibuat, dibayar, diubah, atau dibatalkan, sistem dapat mengirim pesan yang sesuai. Tamu mendapatkan kepastian, sementara tim menerima ringkasan operasional. Template tetap menggunakan tone of voice brand sehingga otomasi terasa cepat tanpa menjadi dingin.",
        "cta": "Otomatisasi informasi rutin, pertahankan manusia untuk pelayanan.",
        "hashtags": "#BookingAutomation #WhatsAppNotification #HospitalityOperations #Lajora",
        "diagram": "automation",
        "steps": ["Booking event", "Template", "WhatsApp", "Email", "Team alert"],
    },
    {
        "format": "CRM",
        "pillar": "Guest relationship",
        "title": "Booking selesai.\nHubungan baru dimulai.",
        "subtitle": "Data tamu dapat membentuk pre-arrival, upsell, feedback, dan repeat booking.",
        "caption": "Guest database membantu bisnis berkomunikasi sesuai tahap perjalanan. Sebelum datang: informasi dan add-on. Saat menginap: bantuan yang relevan. Setelah pulang: feedback dan penawaran kembali. Semua dilakukan dengan persetujuan, segmentasi, dan frekuensi yang sehat.",
        "cta": "Jangan biarkan hubungan berhenti saat checkout.",
        "hashtags": "#HospitalityCRM #GuestExperience #RepeatBooking #Lajora",
        "diagram": "loop",
        "steps": ["Pre-arrival", "Stay", "Feedback", "Return"],
    },
    {
        "format": "Revenue",
        "pillar": "Upselling",
        "title": "Website sendiri membuka\nruang untuk upselling.",
        "subtitle": "Breakfast, transport, experience, dekorasi, dan late checkout dapat ditawarkan di waktu yang tepat.",
        "caption": "Upselling yang baik bukan memaksa tamu membeli lebih banyak. Sistem menampilkan tambahan yang relevan berdasarkan kamar, tanggal, jumlah tamu, dan momen perjalanan. Penawaran dapat muncul saat booking, setelah pembayaran, atau menjelang kedatangan.",
        "cta": "Tambah nilai pengalaman sekaligus nilai transaksi.",
        "hashtags": "#HotelUpselling #AncillaryRevenue #DirectBooking #Lajora",
        "diagram": "growth",
        "steps": ["Room", "Breakfast", "Transfer", "Experience", "Late checkout"],
    },
    {
        "format": "Marketing system",
        "pillar": "Digital funnel",
        "title": "Pemasaran harus terhubung\nsampai ke booking.",
        "subtitle": "Konten menarik perhatian, website membangun keyakinan, sistem menyelesaikan transaksi.",
        "caption": "Konten, iklan, SEO, dan partnership menghasilkan kunjungan. Website mengubah kunjungan menjadi minat. Booking engine dan payment mengubah minat menjadi transaksi. Analytics menunjukkan channel mana yang benar-benar berkontribusi. Tanpa koneksi ini, performa mudah berhenti pada likes dan traffic.",
        "cta": "Ukur perjalanan penuh, bukan hanya bagian atas funnel.",
        "hashtags": "#DigitalFunnel #HospitalityMarketing #BookingConversion #Lajora",
        "diagram": "funnel",
        "steps": ["Reach", "Visit", "Trust", "Book", "Return"],
    },
    {
        "format": "Content framework",
        "pillar": "Social media",
        "title": "Konten hospitality punya\nempat pekerjaan.",
        "subtitle": "Membangun keinginan, memberi bukti, menjawab keraguan, dan mengarahkan tindakan.",
        "caption": "Konten yang hanya memamerkan fasilitas akan cepat terasa seperti katalog. Gunakan empat fungsi: DESIRE untuk membuat orang membayangkan pengalaman, PROOF untuk menunjukkan kenyataan, CLARITY untuk menjawab detail, dan ACTION untuk mengarahkan booking atau percakapan.",
        "cta": "Seimbangkan desire, proof, clarity, dan action.",
        "hashtags": "#ContentSystem #HospitalitySocialMedia #ContentStrategy #Lajora",
        "diagram": "quadrant",
        "steps": ["Desire", "Proof", "Clarity", "Action"],
    },
    {
        "format": "Search",
        "pillar": "SEO",
        "title": "Google membawa tamu\nke pintu digitalmu.",
        "subtitle": "SEO membantu ditemukan; brand dan UX membantu dipilih.",
        "caption": "Website dapat membangun halaman yang menjawab pencarian berdasarkan lokasi, jenis pengalaman, fasilitas, dan kebutuhan tamu. Struktur teknis, kecepatan, konten, profil bisnis, dan ulasan membantu visibilitas. Setelah diklik, pengalaman website menentukan apakah kunjungan berkembang menjadi booking.",
        "cta": "Ditemukan adalah awal. Dipilih adalah tujuan.",
        "hashtags": "#HotelSEO #LocalSEO #HospitalityWebsite #Lajora",
        "diagram": "search",
        "steps": ["Search", "Discover", "Compare", "Trust", "Book"],
    },
    {
        "format": "Analytics",
        "pillar": "Measurement",
        "title": "Apa yang perlu diukur\ndari sistem digital?",
        "subtitle": "Traffic, sumber, conversion, nilai booking, biaya akuisisi, dan repeat guest.",
        "caption": "Dashboard yang berguna tidak harus penuh angka. Mulai dari kunjungan berkualitas, sumber traffic, conversion rate, booking value, abandonment, biaya akuisisi, dan repeat booking. Data tersebut membantu tim menentukan apakah perlu memperbaiki traffic, penawaran, halaman, atau flow pembayaran.",
        "cta": "Ukur angka yang mengubah keputusan.",
        "hashtags": "#HospitalityAnalytics #ConversionTracking #MarketingDashboard #Lajora",
        "diagram": "dashboard",
        "steps": ["Traffic", "Conversion", "Booking value", "Acquisition cost", "Repeat"],
    },
    {
        "format": "Roadmap",
        "pillar": "Implementation",
        "title": "Mulai kecil.\nBangun dengan urutan.",
        "subtitle": "Fondasi brand → website → booking → payment → automation → growth.",
        "caption": "Transformasi digital tidak harus dilakukan sekaligus. Tahap pertama memperjelas brand dan penawaran. Berikutnya membangun website serta booking flow. Setelah transaksi stabil, tambahkan payment automation, CRM, analytics, campaign, dan optimasi. Urutan yang tepat menjaga investasi tetap fokus.",
        "cta": "Prioritaskan bottleneck terbesar, lalu kembangkan sistemnya.",
        "hashtags": "#DigitalRoadmap #HospitalityTransformation #BusinessSystem #Lajora",
        "diagram": "roadmap",
        "steps": ["Brand", "Website", "Booking", "Payment", "Growth"],
    },
    {
        "format": "Comparison",
        "pillar": "Channel strategy",
        "title": "Marketplace dan website\npunya peran berbeda.",
        "subtitle": "Marketplace memperluas jangkauan. Website membangun kendali dan hubungan.",
        "caption": "Marketplace berguna untuk discovery, perbandingan, dan akses ke pasar yang luas. Website sendiri unggul dalam storytelling, fleksibilitas penawaran, data, pengalaman brand, dan repeat guest. Strategi yang sehat menggunakan marketplace sebagai kanal sambil memperkuat aset milik sendiri.",
        "cta": "Kurangi ketergantungan tanpa kehilangan distribusi.",
        "hashtags": "#OTAstrategy #OwnedChannel #DirectBookingStrategy #Lajora",
        "diagram": "comparison",
        "steps": ["Marketplace|Reach & discovery", "Website|Control & relationship"],
    },
    {
        "format": "Integrated system",
        "pillar": "Lajora solution",
        "title": "Sistem yang kuat membuat\nbrand lebih mudah tumbuh.",
        "subtitle": "Branding, website, booking, payment, content, data, dan automation berada dalam satu arah.",
        "caption": "Lajora membangun sistem pertumbuhan hospitality dari fondasi hingga transaksi. Strategi brand memperjelas nilai. Website mengubahnya menjadi pengalaman digital. Booking dan payment menyelesaikan transaksi. Konten mendatangkan perhatian. Data dan automation menjaga hubungan terus bergerak.",
        "cta": "Mulai membangun owned system di lajora.web.id",
        "hashtags": "#Lajora #HospitalitySolution #BrandingSystem #DirectBooking #PaymentGateway",
        "diagram": "ecosystem",
        "steps": ["Brand", "Website", "Booking", "Payment", "Growth"],
    },
]
